source 'https://github.com/CocoaPods/Specs.git'

plugin 'slather'

target 'Tests', :exclusive => true do
  pod 'TBStateMachine', :path => '../'
  pod 'TBStateMachine/DebugSupport', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
