source 'https://github.com/CocoaPods/Specs.git'

#plugin 'slather'

target 'Tests', :exclusive => true do
  pod "TBStateMachine", :path => "../"
  pod "TBStateMachine/DebugSupport", :path => "../"

  pod 'Specta', '~> 0.4'
  pod 'Expecta'
end
