# source 'https://github.com/CocoaPods/Specs.git'

target 'TBStateMachine', :exclusive => true do
  pod "TBStateMachine", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TBStateMachine", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end

begin
    require 'slather'
    Slather.prepare_pods(self)
    rescue LoadError
    puts 'Slather has been disabled (not installed).'
end